CREATE DATABASE IF NOT EXISTS devops_db;

USE devops_db;

CREATE DATABASE IF NOT EXISTS TEST; 

CREATE DATABASE IF NOT EXISTS AMOUNT;

CREATE DATABASE IF NOT EXISTS RUPEES;

CREATE DATABASE IF NOT EXISTS COUNTRY;